spring:
  application:
    name: api
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/tuna}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
  jackson:
    default-property-inclusion: NON_NULL
    
server:
  port: 8080
  servlet:
    context-path: /tuna-api
    
management:
  server:
    port: ${MANAGEMENT_SERVER_PORT:8081}

tuna:
  api:
    keycloak:
      server-url: ${KEYCLOAK_SERVER_URL:https://keycloak.local}
      realm: ${KEYCLOAK_REALM:tuna}
      # the client should enable `Client authentication`, `Direct access grants`
      client-id: ${KEYCLOAK_CLIENT_ID:tuna-api}
      client-secret: ${KEYCLOAK_CLIENT_SECRET:tuna}
