spring:
  application:
    name: api
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/tuna}
    username: ${DB_USERNAME:tuna}
    password: ${DB_PASSWORD:tuna}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

tuna:
  api:
    keycloak:
      server-url: ${KEYCLOAK_SERVER_URL:http://localhost:8080/auth}
      realm: ${KEYCLOAK_REALM:tuna}
      # the client should enable `Client authentication`, `Direct access grants`
      client-id: ${KEYCLOAK_CLIENT_ID:tuna-api}
      client-secret: ${KEYCLOAK_CLIENT_SECRET:tuna}
      debug: ${KEYCLOAK_DEBUG:true}
      username: ${KEYCLOAK_DEBUG_USERNAME:guest}
      password: ${KEYCLOAK_DEBUG_PASSWORD:guest}
      policy-enforcer:
        enabled: ${KEYCLOAK_POLICY_ENFORCER_ENABLED:false}
      
