-- -- Create data_items table
-- CREATE TABLE data_items (
--     id BIGINT AUTO_INCREMENT PRIMARY KEY,
--     name VARCHAR(255) NOT NULL,
--     description TEXT,
--     user_id BIGINT NOT NULL,
--     created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     CONSTRAINT fk_user
--         FOREIGN KEY(user_id)
--         REFERENCES users(id)
--         ON DELETE CASCADE
-- );
